# Generated by Django 5.1.4 on 2026-08-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='unit',
            field=models.CharField(choices=[('reps', 'повторения'), ('kg', 'кг'), ('sec', 'секунды'), ('m', 'метры')], default='reps', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
