# Generated by Django 5.1.4 on 2026-08-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_exercise_unit_workoutsession_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setentry',
            name='weight',
        ),
        migrations.AddField(
            model_name='setentry',
            name='sets_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Подходов'),
        ),
    ]
