# Generated by Django 5.1.4 on 2026-08-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_exercise_owner_reminder_owner_workoutsession_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='monkeytype_apekey',
            field=models.CharField(blank=True, help_text='Личный ApeKey с monkeytype.com/account/settings#apeKeys — для показа своей статистики на вкладке «Печать»', max_length=200, verbose_name='MonkeyType ApeKey'),
        ),
    ]
